name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup 🔧
        uses: actions/setup-node@v1.4.4

      - name: Install ♻
        run: npm install

      - name: Build 🏗
        run: npm run build

      - name: CNAME 🧾
        run: echo sudoku.jonasgeiler.com > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: dist
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
